### ISSUE TITLE
What parameters should I put in MergeTree()?

### ISSUE THREAD

**Issue by linrl3** [Infinidat/infi.clickhouse_orm#125]
I'm using ```MergeTree()``` engine. Does anyone know what parameters should I put in it? Could you give a example?

**Comment by ishirav** [comment]
That really depends on your use case. The parameters in the ORM follow those that ClickHouse supports, so start by reading the ClickHouse docs: https://clickhouse.yandex/docs/en/operations/table_engines/mergetree/

**Comment by linrl3** [comment]
@ishirav The document says that "MergeTree engine does not have parameters." . I got confused...

**Comment by ishirav** [comment]
I guess they mean that you do not pass parameters to the SQL here: `ENGINE = MergeTree()` 
but right afterwards you specify PARTITION BY, ORDER BY etc.

**Comment by linrl3** [comment]
@ishirav Suppose my data model looks like this:
```python
from infi.clickhouse_orm import models, fields
from infi.clickhouse_orm.engines import Memory, MergeTree
class AliMachine(models.Model):
    event_id = fields.StringField()
    event_type = fields.StringField()
    event_product = fields.StringField()
    publish_time = fields.DateTimeField()
    engine = MergeTree('publish_time',('event_id','publish_time'),8192)

```
And I'd like to use MergeTree as my engine, what should I put as parameters in it?  I got the error from this code :``` infi.clickhouse_orm.database.ServerError: Sampling expression must be present in the primary key ```

**Comment by ishirav** [comment]
You can see the parameters expected by the MergeTree class here: https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/docs/class_reference.md#mergetree
The 3rd parameter is sampling_expr, so 8192 got assigned to it instead of the index_granularity.
You can remove the 8192 since that's already the default value of index_granularity.
For clarity, I suggest using the parameter names:

`MergeTree(date_col='publish_time', order_by=('event_id','publish_time'))`

By the way date_col is somewhat obsolete, the newer way of partitioning in ClickHouse is by specifying a partition key (which doesn't have to be date-based). So you should do it like this:

`MergeTree(partition_key=['toYYYYMM(publish_time)'], order_by=('event_id','publish_time'))`
