### ISSUE TITLE
Do we need something like Zookeeper to replicate table?

### ISSUE THREAD

**Issue by linrl3** [Infinidat/infi.clickhouse_orm#127]
I just see some blogs saying that Zookeeper is required for replication, because ```<internal_replication>true</internal_replication>``` would cause problems for replication.

**Comment by emakarov** [comment]
@linrl3 if you are new to the clickhouse ecosystem, then I may suggest to read the official documentation first. Since Zookeeper and Clickhouse settings are not a responsibility of infi.clickhouse_orm
You may read more information about clickhouse and its' settings here:
https://clickhouse.yandex/docs/en/
You may be also interested in joining the Telegram chat of Clickhouse here https://t.me/clickhouse_en
to ask questions related to clickhouse itself.

**Comment by linrl3** [comment]
@emakarov Sry. I am new and post the question in the wrong place. Thanks.
