### ISSUE TITLE
Why ORDER BY in QuerySet by default?

### ISSUE THREAD

**Issue by tsionyx** [Infinidat/infi.clickhouse_orm#40]
Why do you need to ORDER BY all fields in `QuerySet` even when no `order_by` explicitly called. I think this reduces performance of a query.

**Comment by ishirav** [comment]
This is needed so that the results will be sort in a predictable order, otherwise when you paginate through the results you might get the same row in more than one page, or miss some rows. From ClickHouse docs: "If the ORDER BY clause is omitted, the order of the rows is also undefined, and may be nondeterministic".

**Comment by tsionyx** [comment]
Ok, but it's not always necessary to have deterministic order, sometimes I
need only a set of values.

**Comment by ishirav** [comment]
Version 0.9.2 now does not sort queryset results unless you ask for it.
